#!/usr/bin/env bash
# Stand the tracker up on a fresh Ubuntu/Debian VM, as a system service.
#
# Run it from inside a checkout of this repository:
#
#     sudo ./deploy/setup-vps.sh
#
# From the checkout rather than from a URL on purpose — the repository is
# moving to a new account, and a script that clones a hardcoded GitHub URL is a
# script that installs the old copy. Whatever you cloned is what gets installed.
#
# Idempotent: re-run it after a `git pull` to deploy the new code. It will not
# overwrite an existing .env, because that file holds the encryption key every
# stored wallet depends on.
set -euo pipefail

APP_USER=nftmint
APP_DIR=/opt/nftmint
DATA_DIR=/var/lib/nftmint
NODE_MAJOR=22
SERVICE=nftmint-tracker

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33mWARN\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo"

SOURCE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
[ -f "$SOURCE_DIR/package.json" ] || die "run this from inside the repository checkout"

say "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates git rsync openssl >/dev/null

# NodeSource, because the distro's node is usually too old for this project's
# engines field and the failure that produces is an unhelpful syntax error.
if ! command -v node >/dev/null 2>&1 || \
   [ "$(node -p 'process.versions.node.split(".")[0]')" -lt "$NODE_MAJOR" ]; then
  say "Installing Node $NODE_MAJOR"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null
  apt-get install -y -qq nodejs >/dev/null
fi
say "Node $(node -v)"

say "Creating the service user"
# System user, no login shell, no home to speak of: this account exists to own
# one process and one directory.
id -u "$APP_USER" >/dev/null 2>&1 || \
  useradd --system --create-home --home-dir "/home/$APP_USER" --shell /usr/sbin/nologin "$APP_USER"

say "Copying the checkout to $APP_DIR"
mkdir -p "$APP_DIR"
rsync -a --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude 'dist' \
  --exclude '.env' \
  --exclude 'data' \
  --exclude '*.backup.json' \
  "$SOURCE_DIR"/ "$APP_DIR"/

say "Building"
cd "$APP_DIR"
npm ci --no-audit --no-fund
npm run build
# tsx and the test runner are not needed to serve, and every dependency left
# installed is one more thing running as this user.
npm prune --omit=dev

ENV_FILE="$APP_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  say "Keeping the existing .env"
else
  say "Writing a first .env"
  # Both secrets are generated here rather than left blank, because a blank
  # ACCOUNT_ENCRYPTION_KEY is the one setting that cannot be fixed later: change
  # it after wallets exist and every one of them becomes unopenable.
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NETWORK=mainnet
PORT=8080
TRACKER_HOST=0.0.0.0
DATA_DIR=$DATA_DIR

# Shared with whatever reads this tracker. On the Vercel side this same value
# goes in TRACKER_UPSTREAM_TOKEN.
TRACKER_AUTH_TOKEN=$(openssl rand -hex 32)

# Seals every generated wallet. If you are MOVING an existing deployment here,
# replace this with the key from the old one before importing anything —
# otherwise the imported wallets cannot sign, and whatever is funded in them is
# stranded.
ACCOUNT_ENCRYPTION_KEY=$(openssl rand -hex 32)
EOF
fi
chown "$APP_USER:$APP_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

say "Preparing $DATA_DIR"
mkdir -p "$DATA_DIR"
chown "$APP_USER:$APP_USER" "$DATA_DIR"
# 0700 because the accounts file in here holds sealed wallet keys, and every
# other account on this box has no business reading them.
chmod 700 "$DATA_DIR"

say "Installing the service"
install -m 0644 "$APP_DIR/deploy/$SERVICE.service" "/etc/systemd/system/$SERVICE.service"
systemctl daemon-reload
systemctl enable "$SERVICE" >/dev/null
systemctl restart "$SERVICE"

say "Waiting for it to answer"
token=$(grep -E '^TRACKER_AUTH_TOKEN=' "$ENV_FILE" | cut -d= -f2-)
port=$(grep -E '^PORT=' "$ENV_FILE" | cut -d= -f2- || echo 8080)
ok=false
for _ in $(seq 1 20); do
  if curl -fsS -H "Authorization: Bearer $token" "http://127.0.0.1:${port:-8080}/api/health" >/dev/null 2>&1; then
    ok=true
    break
  fi
  sleep 1
done

if [ "$ok" = true ]; then
  say "Tracker is up"
  curl -fsS -H "Authorization: Bearer $token" "http://127.0.0.1:${port:-8080}/api/health"
  echo
else
  warn "No answer on 127.0.0.1:${port:-8080} yet. Check: journalctl -u $SERVICE -n 50 --no-pager"
fi

cat <<EOF

$(printf '\033[1mNext\033[0m')

  Logs        journalctl -u $SERVICE -f
  Restart     systemctl restart $SERVICE
  Token       grep TRACKER_AUTH_TOKEN $ENV_FILE

  The tracker listens on all interfaces but nothing is open to the internet yet,
  and it should not be opened directly: the token travels on every request from
  Vercel, so it needs TLS in front of it. Two ways, both free:

    A domain you own   install Caddy and reverse-proxy /api/* to 127.0.0.1:$port
                       (deploy/Caddyfile is the config; TLS is automatic)
    No domain          cloudflared tunnel — no inbound port opens at all

  Then set these on the Vercel side:

    TRACKER_UPSTREAM_URL=https://<that hostname>
    TRACKER_UPSTREAM_TOKEN=<the token above>

  On Oracle Cloud, opening a port takes two steps: the VCN security list AND
  the instance's own iptables rules, which their Ubuntu image ships locked down.
  A tunnel avoids both.

  docs/MIGRATION.md has the rest, including moving existing accounts here.
EOF
